#!/usr/bin/env bash

# Arranges the files by grouping them into folder of their extension name
# TODO: Run this script in your downloads folder

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require fd
require egrep

declare -A special_cases=(

    ['\.(jpg|jpeg|png|gif|bmp)$']='pictures'                
    ['\.(mp4|mkv|avi|mov|flv)$']='videos'                 
    ['\.(pdf|doc|docx|txt)$']='docs'  
    ['\.(tar\.gz|tgz|tar\.bz2|tbz|tar\.xz|txz)$']='tars'    
    ['\.(zip|rar|7z)$']='archives'
    ['^*.(mp3|wav|flac)$']='music'
    ['^*.(py|js|java)$']='programs'

    # TODO: Add your own pattern here for similar file types appropriately
    # Refer https://regex101.com/ & https://github.com/ziishaned/learn-regex/ for explaination and writing patterns
    # These (regex) are same as ones used in sed command
)

fd -tf -d1 \
| while read file; do
    folder="$PWD/${file##*.}"
    for regex in "${!special_cases[@]}"; do
        (echo "$file" | egrep -q "$regex") && {
            folder="$PWD/${special_cases[$regex]}"
            break
        }
    done

    mkdir -p "$folder"
    mv "$file" "$folder"
done

