#!/usr/bin/env bash

# Issue: Implement Password Generation Functions
# Description:
# Create a function that generates passwords, The password should consist of uppercase letters, lowercase letters, numbers, and special characters. The function should take in a single argument, which is the length of the password to generate. The function should return the generated password.
new_password() {
    local length=$1
    local characters='A-Za-z0-9!@#$%^&*()_+[]{}<>?,./-'
    local pass
    pass=$(tr -dc "${characters}" < /dev/urandom | head -c "$length")
    echo "$pass"
}

password=$(new_password 10)
echo "Generated Password: $password"
