#!/usr/bin/env bash

# TODO: Make it print out permissions of the given files in octal format

for file in "$@"; do
    if [ -e "$file" ]; then
        perms=$(stat -c "%a" "$file")
        echo "$file : $perms"
    else
        echo "$file : file not found"
    fi
done

# E.g.:
# $ perms weather ../README.md
# 775 weather
# 664 ../README.md

