#!/usr/bin/env bash

fd --type f --exec test -x {} \; --no-extension -delete
echo "Deleted all the binaries in the current directory"

# Remove all the binary files (usually made after gcc) present inside current directory
# Refer "man find" for more information, you can also use modern tool like fd instead of find
